site_name: Hello World!
nav:
    - Home: 
        - Overview: index.md
    - Architecture: 
        - Intro: architecture.md
    - Development:
        - Code: code.md
theme:
  name: material
  features:
    - navigation.tabs  
